### ISSUE TITLE
Dependency count seems inaccurate sometimes

### ISSUE THREAD

**Issue by natecraddock** [pixqc/ziglist#3] opened 2024-08-16 14:07 UTC
Wonderful index of Zig projects, thank you for the work! It is very well designed.

<img width="342" alt="image" src="https://github.com/user-attachments/assets/b2183047-185e-4651-a6cd-479822b2be8f">

Just wanted to point out that the dependency count seems to be off. When I go to the [dependencies](https://ziglist.org/dependencies) page it correctly lists the 6 deps in the zon file, but the home/index page says +61 more which I find interesting.

<img width="346" alt="image" src="https://github.com/user-attachments/assets/96de6d51-5e75-48da-931a-2172ddd002a0">

And this project only has a dep on vaxis but it is listed 5 times, with 7 more hidden.

Maybe whatever is indexing is _adding_ to the deps list rather than replacing it?

**Comment by pixqc** [comment] 2024-08-16 14:45
Yeah there was a bug on /search that listed duplicate dependencies. Could you give it another go? It looks good on me now.
<img width="687" alt="image" src="https://github.com/user-attachments/assets/6d4873f2-23fb-4d70-85fc-f6c0a5e60211">

**Comment by natecraddock** [comment] 2024-08-16 15:26
Wow you're fast!

I'm still seeing some duplicates. Fewer than before though

<img width="1092" alt="image" src="https://github.com/user-attachments/assets/661a0b5e-0395-42b2-b6db-81c1097f071d">

**Comment by pixqc** [comment] 2024-08-16 15:39
Okay I think I've repro'd it locally. My hunch says something's wrong with the select query

<img width="354" alt="image" src="https://github.com/user-attachments/assets/e5ebe886-77b7-4d3a-b4bd-38441181c56f">

**Comment by pixqc** [comment] 2024-08-16 16:18
The issue is because SQLite's full text search virtual table doesn't enforce unique constraint, and the previous code just inserted dupes into the table. That's why the dupe only shows on search, but not on dependencies.

Should be fixed on: https://github.com/pixqc/ziglist/commit/cd5c51abea02ca34c97404eae63fc7c58a761ae1

I've tried intentionally inserted two ziglang/zig to the virtual table on prod and there are no dupes.

<img width="354" alt="image" src="https://github.com/user-attachments/assets/38391e8b-3c5c-46f1-be44-664a441a7b2c">

Pretty sure the issue is fixed, but please re-open if you still see the dupes again!

**Closed by pixqc** 2024-08-16 16:18 UTC

**Comment by natecraddock** [comment] 2024-08-16 16:23
🙌 looks perfect! Wonderful fast fix
